
namespace ScriptItemsMarker;

#pragma warning disable CA1416

using System;
using Mutagen.Bethesda.WPF.Reflection.Attributes;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using System.IO;
using System.Linq;
using Newtonsoft.Json;
using Noggog;
using static Mutagen.Bethesda.FormKeys.SkyrimSE.Skyrim.Keyword;
using System.Threading.Tasks;

public class Settings
{
  [SettingName("Mod name")]
  [Tooltip("Full name including extension")]
  public string ModName = "SomeEsp.esp";
  
  [SettingName("Keyword Form Id")]
  [Tooltip("Form Id of keyword in mod")]
  public ulong FormId = 0x800;
}

public static class Program
{
  static Lazy<Settings> _settings = new();
  public static async Task<int> Main(string[] args)
  {
    return await SynthesisPipeline.Instance.AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
      .SetAutogeneratedSettings(nickname: "settings", path: "settings.json", out _settings)
      .SetTypicalOpen(GameRelease.SkyrimSE, new ModKey("ScriptItemsMarker.esp", ModType.Plugin))
      .Run(args);
  }

  private static void SynthesisLog(string message, bool special = false)
  {
    if (special)
    {
      Console.WriteLine();
      Console.Write(">>> ");
    }

    Console.WriteLine(message);
    if (special) Console.WriteLine();
  }

  private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
  {
    var modName = _settings.Value.ModName;
    var formId = _settings.Value.FormId;
    
    SynthesisLog($"Item Weight Configuration: {modName} {formId}", true);


    SynthesisLog("Done patching script items marker!", true);
  }
}